Modify Nested field to handle the combination of many=True and allow_…
marshmallow-code/marshmallow pull request #1498
Opened 2020-01-31 23:32 UTC by Meallia

Fix for #1497 
Hi,

I tried to fix the issue by modifying `Schema` as suggested in the issue discussion but it would fail to detect validation errors when `[None]` is passed to a `Nested(many=True, allow_none=False)` field as the schema is not aware of `allow_none`. 

Instead, I made the `Nested` field check when (de-)serializing if `many` and `allow_none` are both set to `True`. in that case, we simply pass the non-`None` values to the underlying schema then insert `None` values back in the resulting list.

2020-02-03 15:08 UTC, deckar01 commented
> it would fail to detect validation errors when `[None]` is passed to a `Nested(many=True, allow_none=False)`

That is existing behavior and orthogonal to #1497.

2020-02-03 15:38 UTC, deckar01 requested changes

2020-02-03 15:38 UTC, deckar01 commented on tests/test_deserialization.py
> +        assert field.deserialize([None, {}]) == [None, {}]
The `allow_none` argument on `Nested` applies to the `Nested` container, not its children. Depending on `many` this is either a `List`, or a pass through container.

https://marshmallow.readthedocs.io/en/stable/api_reference.html#marshmallow.fields.Nested

Use `List(Nested(allow_none))` instead. #779 is an RFC that is amassing reasons `Nested(many)` should be deprecated. I will add this to the list.

2020-02-04 21:26 UTC, Meallia commented
Oh, yes, you're absolutely right about allow_none for nested attributes. So I guess we only need to revert the optimisation on lists of nested attributes.

Is this merge request still relevant then ?

Sorry for the delay, I could not find the time to follow up on the related issue but I will I'm the coming days.

2020-02-19 10:39 UTC, lafrech commented
#1497 was fixed by #1503.

2020-02-19 10:39 UTC, closed without merging