Better example of check_unknown_fields validator
marshmallow-code/marshmallow pull request #559
Opened 2016-12-11 18:58 UTC by altaurog

Include all unknown fields in the error message.  The current example
reports at most one, even if more are present.  Fixes #558

2016-12-11 22:24 UTC, maximkulkin requested changes

2016-12-11 22:24 UTC, maximkulkin commented on docs/extending.rst
> +                raise marshmallow.ValidationError(errors)
How about using ValidationError structure to point (machine-readable) to fields that have error?!
```python
raise marshmallow.ValidationError('Unknown field', list(unknown))
```
The reported result would be in a dictionary form like this:
```python
{'unknown_field1': 'Unknown field', 'unknown_field2': 'Unknown field'}
```

2016-12-12 06:42 UTC, altaurog commented on docs/extending.rst
> +                raise marshmallow.ValidationError(errors)
Oh.  I see.  Yes, that makes sense.   `list` is superfluous then, as `set` is already iterable.

2016-12-12 09:24 UTC, maximkulkin approved these changes
LGTM 👍  Just make sure to squash all commits into one before merging

2016-12-18 18:42 UTC, sloria commented
Thanks!

2016-12-18 18:42 UTC, merged