strict value is overidable, in all case. (especially,  __init__(strict=False), and Meta.strict=True)
marshmallow-code/marshmallow pull request #569
Opened 2017-01-06 15:03 UTC by podhmo

Current marshmallow's implementation is not allow to overwrite strict value by `strict=False`, when strict value is set by Meta.

```python
class S(Schema):
    class Meta:
        strict = True

S(strict=False).strict  # => True
```
this pull request is the solution for #550

2017-01-06 15:14 UTC, podhmo commented
It is a bit strange that default value of strict is `None`.  If so, it is better like below.

```python
delegated = object()

class BaseSchema(base.SchemaABC):
    .. snip
    def __init__(self, extra=None, only=(), exclude=(), prefix='', strict=delegated,
                 many=False, context=None, load_only=(), dump_only=(),
                 partial=False):
```

2017-01-06 20:29 UTC, maximkulkin requested changes
I think there is no need for custom object as default value implementation and using None instead is OK. See my inline comments though.

2017-01-06 20:29 UTC, maximkulkin commented on tests/test_schema.py
> +    def test__meta_true(self):
1. I think it is safe and more common not to use double underscores in test names.
2. You miss two tests when you use SchemaWithoutMeta and override with init argument (both True and False).

2017-01-07 02:18 UTC, podhmo commented
Oh, yes I missed, adding two tests. And renaming test name (honestly, this is something like my individual habits,  separating test method's name by double underscore for readability. But this is not strong will).

2017-01-07 03:31 UTC, maximkulkin commented
👍 LGTM

Just make sure to squash your 3 commits about tests into one before merging, their commit descriptions are not informative and it is completely unnecessary to have all this small fixes in master.

2017-01-07 09:04 UTC, podhmo commented
sure. rebased.

2017-01-08 15:41 UTC, sloria commented
Thanks @podhmo for the PR and thanks @maximkulkin . @podhmo : would you mind adding yourself to `AUTHORS.rst`? Once that's done, this is good to merge.

I consider this a bugfix, so I'll backport this to the 2.10-line branch once this is merged.

2017-01-08 20:32 UTC, podhmo commented
added.

2017-01-08 21:16 UTC, sloria commented
Thanks!

2017-01-08 21:16 UTC, merged