Allow deeply nested load and dump only
marshmallow-code/marshmallow pull request #572
Opened 2017-01-18 00:34 UTC by YuriHeupa

This allows deeply nested `load_only` and `dump_only` for `Nested` fields, it takes declarations from parent and normalizes it passing to the Nested schema defined.

For example:
```python
class ChildSchema(Schema):
    foo = fields.String()
    bar = fields.String()

class ParentSchema(Schema):
    childs = NestedDumpOnly('ChildSchema')

ParentSchema(dump_only=('childs.foo', ))
# The Above will mark the ChildSchema.foo field as dump_only=True
```

2017-01-18 00:42 UTC, maximkulkin requested changes

2017-01-18 00:42 UTC, maximkulkin commented on marshmallow/fields.py
> +                     if nested_field in field]
Shouldn't this be `if field.startswith(nested_field)` ?

2017-01-18 00:42 UTC, maximkulkin commented on marshmallow/fields.py
> +        nested_field = '%s.' % self.name
This implementation has performance impact of calculating this every time schema is requested although schema itself is being cached. I suggest moving this into two functions and call them whenever you create schema class.

2017-01-18 00:49 UTC, YuriHeupa commented on marshmallow/fields.py
> +                     if nested_field in field]
Make sense, fixed.

2017-01-18 00:50 UTC, YuriHeupa commented on marshmallow/fields.py
> +        nested_field = '%s.' % self.name
Indeed. I've made changes based on your suggestion, please let me know if it makes sense to you.

2017-01-18 00:50 UTC, maximkulkin requested changes

2017-01-18 00:50 UTC, maximkulkin commented on marshmallow/fields.py
> +                if nested_field in field.startswith(nested_field)]
This thing is incorrect

2017-01-18 00:51 UTC, YuriHeupa commented on marshmallow/fields.py
> +                if nested_field in field.startswith(nested_field)]
Fixed.

2017-01-18 00:55 UTC, maximkulkin approved these changes

2017-01-18 00:55 UTC, maximkulkin commented on marshmallow/fields.py
> +                for field in getattr(self.parent, option_name, set(()))
Although I do not understand why there is so much parens in `set()` call, I guess it's minor.

2017-01-18 01:01 UTC, YuriHeupa commented on marshmallow/fields.py
> +                for field in getattr(self.parent, option_name, set(()))
🤔  They were unnecessary. removed!

2017-01-20 19:58 UTC, YuriHeupa commented
Is there any plan or objection for merging this?

2017-01-20 20:03 UTC, sloria commented
This looks like a good feature. Thanks for the PR and thanks @maximkulkin for reviewing. I'll get to reviewing and merging this soon, once I have a moment of free time.

2017-01-21 21:30 UTC, sloria approved these changes
Looks great. Thanks again!

2017-01-21 21:30 UTC, merged

2017-01-23 09:08 UTC, avish commented
Uhm, this change seems to be breaking list-of-nested fields (i.e. a `Nested` field whose `parent` is a `List` field rather than a `Schema`, which means its `load_only` and `dump_only` properties contain boolean values rather than sets): 

```
from marshmallow import Schema
from marshmallow import fields

class ChildSchema(Schema):
    name = fields.Str()

class ParentSchema(Schema):
    children = fields.List(fields.Nested(ChildSchema))

def test_list_of_nested():
    data = {'children': [{'name': 'Child'}]}
    ParentSchema().dump(data)

```

Gives: 
> TypeError: 'bool' object is not iterable

2017-01-23 14:42 UTC, YuriHeupa commented
@avish Thanks for reporting this, I've submitted a fix here #575

2017-01-27 23:14 UTC, touilleMan commented
I've encountered another cornercase where this feature break (see https://travis-ci.org/Scille/umongo/jobs/195873309#L493)

```python
    @property
    def root(self):
        """Reference to the `Schema` that this field belongs to even if it is buried in a `List`."""
        ret = self
        while hasattr(ret, 'parent') and ret.parent:
            ret = ret.parent
        return ret
```

Basically if a nested field has no parent (not linked yet to a schema), then `field.root` will return itself... who's `load_only`/`dump_only` fields are boolean !

I think `root` implementation is broken : it should not return itself but `None` if the field has no schema.
Once this behavior fixed `_nested_normalized_option` should work properly :smile:

2017-01-28 02:21 UTC, YuriHeupa commented
@touilleMan I'm not sure if that's the correct approach for fixing this issue, but I've submitted a fix here #578