Allow Number fields to prohibit boolean values.
marshmallow-code/marshmallow pull request #635
Opened 2017-05-24 19:02 UTC by rowillia

After a bunch of research, I decided to _explicitly_ special case booleans as opposed
to adding a flag for only allowing numbers to be serialized.  I came across code in
our repositories that, for example, overload `__int__` or `__float__` that would expect
to be able to be serialized.  I agree, however, that allowing booleans to be serialized
as numbers is likely incorrect.

This fixes https://github.com/marshmallow-code/marshmallow/issues/623

2017-05-26 01:32 UTC, sloria requested changes

2017-05-26 01:32 UTC, sloria commented on marshmallow/fields.py
> +    :param bool prohibit_boolean: If True, attempting to serialize a boolean
I don't think we need to add this as a parameter. `Number` should only accept numbers as input; booleans should be considered invalid.

2017-05-26 01:33 UTC, sloria commented
Thanks for the PR! Just one suggestion above.

2017-05-31 04:38 UTC, rowillia commented
@sloria Done!

2017-06-02 11:21 UTC, sloria approved these changes

2017-06-02 11:21 UTC, sloria commented
Thanks!

2017-06-02 11:21 UTC, merged