Fix corner case with unknown!=EXCLUDE and decorated processor returns None
marshmallow-code/marshmallow pull request #857
Opened 2018-06-27 13:17 UTC by lafrech

2018-06-27 13:19 UTC, lafrech commented
Not really a corner case since `RAISE` shall become default.

2018-06-27 16:17 UTC, lafrech commented
Hold this. It is a bit more complicated than I first thought.

It is not only the about the `None` case but about all wrong data types.

Current approach is to iterate on fields and get keys from input data. If data has no get method, then `AttributeError` is caught and an error is stored.

There are a few issues with this:

- When `unknown != EXCLUDE`, the code that handles unknown keys fails as `data` is not iterable and `set(data)` won't work. This is what brought me here in the first place.
- The error message for this is the "type" error message from the first field that triggers this, while this is a schema error. It does not really make sense IMHO to pick a random `Field` error message for a schema error.
- If the schema has no field, no error is triggered. A schema without field might not be an obvious use case, but why not? It could make sense when used with `unknown=INCLUDE`, or it could be a corner case of dynamically creating `Schema`s.

I added two commits showing two different approaches to this.

The first catches the `TypeError` when dealing with unknown fields and skips the treatment. It looks awkward and redundant. And it only addresses the first issue in the list above.

The second checks the type of `data` before doing anything. It adds a check to the normal execution path rather than relying solely on try/catch, which is not ideal in terms of performance, but not _that_ bad. Also, it works with `AttributeError`. If `data` has a `get` method but is not an iterable, it is bound to fail. This might not be an issue in practice. I mean it will only break if you try hard. And the `'Invalid input type'` error message is hardcoded.

This reveals underlying design issues. It is not the simple change I thought. (And I came there while trying to tackle https://github.com/marshmallow-code/marshmallow/issues/851...)

Thoughts welcome.

2018-06-27 16:37 UTC, lafrech commented
In fact, the whole wrong data type case management is smelly from the start:

```python
                errors = self.get_errors(index=index)
                msg = field_obj.error_messages['type'].format(
                    input=data, input_type=data.__class__.__name__,
                )
                self.error_field_names = [SCHEMA]
                errors = self.get_errors()
                errors.setdefault(SCHEMA, []).append(msg)
```

We're trying to fit a schema error in a mechanism that was meant for field errors. And the logic here is a bit twisted: the first call to `get_errors` mutates `self.errors` so it can't be removed, which is not obvious when reading this part of the code.

Perhaps `store_error` / `get_errors` need refactoring and should provide a clean interface to store schema errors.

This looks quite like a WWdD issue...

2018-07-01 15:29 UTC, sloria commented
> We're trying to fit a schema error in a mechanism that was meant for field errors. 

I agree that it's awkward right now. We should come up with a solution to configure both "invalid type" and "unknown field" (#852) error messages on the Schema class.

> the first call to get_errors mutates self.errors so it can't be removed, which is not obvious when reading this part of the code.

Yeah, it's not ideal. Either `get_errors` should be renamed or we should separate the mutation of `self.errors` from it.

2018-07-01 16:55 UTC, sloria commented on marshmallow/marshalling.py
> +            data.get('dummy', missing)
I think doing `if isinstance(data, collections.Mapping)` is more appropriate in this case.

2018-07-01 17:04 UTC, sloria commented on marshmallow/marshalling.py
> +            msg = 'Invalid input type.'
This is fine for now until #852 is addressed. Might as well remove `'type'` in `Field.default_error_messages` while you're at it.

2018-07-01 17:05 UTC, sloria requested changes
Just a couple suggestions: using `isinstance` insead of EAFP for checking the data type, and removing `type` from default error messages.

2018-07-01 21:45 UTC, lafrech commented
Suggestions applied. Rebased.

2018-07-02 03:22 UTC, sloria approved these changes

2018-07-02 03:22 UTC, merged