Fixes for #906 (TypeError with many=True) and #907 (return [] not {} on many=True error) and #930 (disallows strings and dicts on many=True)
marshmallow-code/marshmallow pull request #954
Opened 2018-09-16 21:18 UTC by lafrech

#910 + minor rework

2018-09-16 23:14 UTC, sloria requested changes
Looks good. Just a few suggestions re: tests. Once those are addressed, this can be merged.

2018-09-16 23:14 UTC, sloria commented on tests/test_schema.py
> +    def test_non_iterables_with_many(self, val):
This test appears misplaced: it's not really about field validation, as the class name suggests. Perhaps this can just be a top-level test function.

2018-09-16 23:14 UTC, sloria commented on tests/test_schema.py
> +def test_load_many_input_types():
This is largely redundant with `test_non_iterables_with_many`. Maybe remove this in favor of that one, and separate out the empty collection cases (`s.load([])` and `s.load(set())`) into a separate test function.

2018-09-17 07:41 UTC, lafrech commented
See updated tests.

I noticed another discrepancy between List(Nested) and Nested(many=True). See the TODO in the tests.

```py
@pytest.mark.parametrize('val', (False, 1, 1.2, object(), {}, {'1': 2}, 'lol'))
def test_load_many_in_nested_invalid_input_type(val):
    class Inner(Schema):
        name = fields.String()
    class Outer(Schema):
        list1 = fields.List(fields.Nested(Inner))
        list2 = fields.Nested(Inner, many=True)
    with pytest.raises(ValidationError) as e:
        Outer().load({'list1': val, 'list2': val})
    # TODO: Error messages should be identical (#779)
    assert e.value.messages == {'list1': ['Not a valid list.'], 'list2': ['Invalid type.']}
```

Unless you think of a quick fix, we can add it to #779 and merge this.

2018-09-18 02:33 UTC, sloria approved these changes

2018-09-18 02:33 UTC, sloria commented
Let's defer the error message discrepancy for now and get this merged.

2018-09-18 02:34 UTC, merged

2018-09-19 00:56 UTC, sloria commented
Hm, on further review, I don't think this should be backported to 2.x.

We decided that raising an error when deserializing None (#511) was a backwards-incompatible change, and this is a similar change.

As for `valid_data`--that doesn't exist in 2.x.

2018-09-19 07:43 UTC, lafrech commented
I think #906 is a bug and could be fixed in 2.x.

```py
        if many and data is not None:
            self._pending = True
            ret = [self.deserialize(d, fields_dict, many=False,
                        partial=partial, dict_class=dict_class,
                        index=idx, index_errors=index_errors)
                        for idx, d in enumerate(data)]
```

If `data` is not "a sequence, an iterator, or some other object which supports iteration", enumerate will raise a `TypeError`. Fixing this wouldn't be a breaking change (unless someone relies on a `TypeError` being raised...).

This only affects `Schema(many=True)`, not `Nested(many=True)`. The test in `Nested(many=True)` is

```py
        if self.many and not utils.is_collection(value):
            self.fail('type', input=value, type=value.__class__.__name__)
```

AFAIU, this is not a security issue. I probably won't affect most APIs as on POST or PUT, you don't expect a plurality of items to be sent. Worst case scenario, you get a 500 error, not some data being leaked.

2018-09-20 03:22 UTC, sloria commented
@lafrech Good point. Backport for the #906 fix is in #959 .